# Generated by Django 3.2.18 on 2023-03-04 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quadraLote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('banco', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('valor_devido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cpf_cnpj', models.CharField(max_length=100)),
                ('total_recebido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('formas_pagamento', models.TextField(blank=True, null=True)),
                ('transacao', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_contrato', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_devedor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debito_intercalada', models.CharField(blank=True, max_length=100, null=True)),
                ('preco_intercalada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('numero_intercaladas', models.IntegerField(blank=True, null=True)),
                ('debito_parcelas_aas', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_parcelas_aas', models.IntegerField(blank=True, null=True)),
                ('preco_carne', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('parcelas', models.IntegerField()),
                ('entrada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacoes', models.CharField(blank=True, max_length=100, null=True)),
                ('situacao', models.CharField(blank=True, max_length=100, null=True)),
                ('vencimento', models.DateField()),
                ('valor_a_receber', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('numero_boleto_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_boleto_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('data_contrato', models.DateField()),
                ('codigo_parcela', models.CharField(max_length=100)),
                ('parcela', models.IntegerField()),
                ('tipo_parcela', models.CharField(max_length=100)),
                ('data_vencimento', models.DateField()),
                ('valor_corrigido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('fracao_ideal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('indexador', models.CharField(max_length=100)),
                ('taxa_juros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_venda', models.DateField()),
                ('cpf_cnpj_comprador', models.CharField(max_length=100)),
                ('nome_comprador', models.CharField(max_length=100)),
                ('data_habite_se', models.DateField(blank=True, null=True)),
                ('performado', models.CharField(max_length=100)),
                ('bloco', models.CharField(max_length=100)),
                ('unidade', models.CharField(max_length=100)),
                ('fase', models.CharField(max_length=100)),
                ('empreendimento', models.CharField(max_length=100)),
                ('codigo_contrato_id', models.CharField(max_length=100)),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('excluido', models.BooleanField(default=False)),
                ('data_exclusao', models.DateTimeField(blank=True, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quadraLote.lote')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
            },
        ),
    ]
