# Generated by Django 3.2.18 on 2023-05-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0003_alter_entrada_parcela'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='tipo_transferencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
