# Generated by Django 3.2.18 on 2023-05-18 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_auto_20230427_2237'),
        ('entrada', '0004_auto_20230517_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ClienteEntrada', to='cliente.cliente', verbose_name='cliente'),
        ),
    ]
