# Generated by Django 3.2.18 on 2023-05-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0005_entrada_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='data',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
