# Generated by Django 3.2.18 on 2023-03-04 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quadra', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Quadra',
                'verbose_name_plural': 'Quadras',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=100)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parcelamento_id', models.CharField(max_length=100)),
                ('aditivo_de_alteracao', models.CharField(max_length=100)),
                ('numero_da_matricula', models.CharField(max_length=100)),
                ('data_de_venda', models.DateField()),
                ('periodicidade_de_reajuste', models.CharField(max_length=100)),
                ('sistema_de_amortizacao', models.CharField(max_length=100)),
                ('taxa_de_juros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('indexador_apos_habitase', models.CharField(max_length=100)),
                ('indexador_ate_habitase', models.CharField(max_length=100)),
                ('prazo_total', models.IntegerField()),
                ('valor_de_financiamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_de_avaliacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_de_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fracao_ideal', models.CharField(max_length=100)),
                ('nome_do_empreendimento', models.CharField(max_length=100)),
                ('spe', models.CharField(max_length=100)),
                ('tipo_de_contrato', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('tipo_de_imovel', models.CharField(max_length=100)),
                ('cpf_cnpj', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('nome_devedor', models.CharField(max_length=100)),
                ('tipos_de_cliente', models.CharField(max_length=100)),
                ('codigo_de_contrato', models.CharField(max_length=100)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('quadra_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quadraLote.quadra')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
    ]
