# Generated by Django 3.2.18 on 2023-04-22 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quadraLote', '0002_auto_20230422_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lote',
            old_name='cliente_id',
            new_name='cliente',
        ),
    ]
