# Generated by Django 3.2.18 on 2023-04-22 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quadraLote', '0003_rename_cliente_id_lote_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='quadra_Id',
        ),
        migrations.AddField(
            model_name='lote',
            name='quadra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='QuadraLote', to='quadraLote.quadra', verbose_name='quadra'),
        ),
    ]
