# Generated by Django 3.2.18 on 2023-04-23 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20230318_1255'),
        ('quadraLote', '0004_auto_20230422_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ClienteLote', to='cliente.cliente', verbose_name='cliente'),
        ),
    ]
