# Generated by Django 3.2.18 on 2023-05-17 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quadraLote', '0005_lote_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lote',
            old_name='cpf_cnpj',
            new_name='numero_contrato',
        ),
    ]
