# Generated by Django 3.2.18 on 2023-05-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quadraLote', '0006_rename_cpf_cnpj_lote_numero_contrato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lote',
            old_name='valor_de_financiamento',
            new_name='valor_financiamento_pos',
        ),
        migrations.AddField(
            model_name='lote',
            name='valor_financiamento_pre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
