# Generated by Django 3.2.18 on 2023-06-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quadraLote', '0007_auto_20230517_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadra',
            name='residencial',
            field=models.CharField(default='residencial lagoa', max_length=100),
            preserve_default=False,
        ),
    ]
