# Generated by Django 3.2.18 on 2023-06-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quadraLote', '0008_quadra_residencial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='disponibilidade',
            field=models.BooleanField(default=True),
        ),
    ]
