# Generated by Django 3.2.18 on 2023-06-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quadraLote', '0009_lote_disponibilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='data_de_habita',
            field=models.DateField(blank=True, null=True),
        ),
    ]
