# Generated by Django 3.2.18 on 2023-06-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quadraLote', '0010_lote_data_de_habita'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='data_parcelas',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='numero_parcelas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='valor_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
