# Generated by Django 3.2.18 on 2023-03-04 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('quadraLote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=50)),
                ('situacao', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quadraLote.lote')),
            ],
            options={
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
