# Generated by Django 3.2.18 on 2023-05-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
