# Generated by Django 3.2.18 on 2023-06-22 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quadraLote', '0008_quadra_residencial'),
        ('documento', '0003_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='lote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quadraLote.lote'),
            preserve_default=False,
        ),
    ]
