# Generated by Django 3.2.18 on 2023-06-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_cliente_profissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
