# Generated by Django 3.2.18 on 2023-03-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControleFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.CharField(max_length=100)),
                ('dias', models.CharField(choices=[('Segunda', 'Segunda-feira'), ('Terca', 'Terça-feira'), ('Quarta', 'Quarta-feira'), ('Quinta', 'Quinta-feira'), ('Sexta', 'Sexta-feira')], max_length=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('periodo', models.DateField()),
            ],
        ),
    ]
