# Generated by Django 3.2.18 on 2023-03-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleFuncionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlefuncionario',
            name='dias',
            field=models.CharField(choices=[('Segunda', 'Segunda-feira'), ('Terca', 'Terça-feira'), ('Quarta', 'Quarta-feira'), ('Quinta', 'Quinta-feira'), ('Sexta', 'Sexta-feira'), ('Sabado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10),
        ),
    ]
