# Generated by Django 3.2.18 on 2023-05-18 02:35

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('controleFuncionario', '0002_alter_controlefuncionario_dias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlefuncionario',
            name='periodo',
        ),
        migrations.AddField(
            model_name='controlefuncionario',
            name='data_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlefuncionario',
            name='data_inicial',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='controlefuncionario',
            name='dias',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Segunda', 'Segunda-feira'), ('Terca', 'Terça-feira'), ('Quarta', 'Quarta-feira'), ('Quinta', 'Quinta-feira'), ('Sexta', 'Sexta-feira'), ('Sabado', 'Sábado'), ('Domingo', 'Domingo')], max_length=48),
        ),
    ]
