# Generated by Django 3.2.18 on 2023-03-04 18:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quadraLote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_restituicao', models.DateTimeField(default=django.utils.timezone.now)),
                ('valor_restituir', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parcelamento', models.CharField(max_length=100)),
                ('parcela', models.IntegerField()),
                ('excluido', models.BooleanField(default=False)),
                ('data_exclusao', models.DateTimeField(blank=True, null=True)),
                ('lote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quadraLote.lote')),
            ],
            options={
                'verbose_name_plural': 'Devolucoes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DevolucaoParcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_referencia', models.DateField()),
                ('data_pagamento', models.DateField()),
                ('excluido', models.BooleanField(default=False)),
                ('data_exclusao', models.DateTimeField(blank=True, null=True)),
                ('devolucao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devolucao.devolucao')),
            ],
            options={
                'verbose_name_plural': 'DevolucoesParcela',
                'ordering': ['id'],
            },
        ),
    ]
