# Generated by Django 3.2.18 on 2023-03-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControleCheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_id', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('banco', models.CharField(max_length=100)),
                ('agencia', models.CharField(max_length=100)),
                ('conta_corrente', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
                ('vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=100)),
                ('observacoes', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Controle de Cheque',
                'verbose_name_plural': 'Controle de Cheques',
            },
        ),
    ]
