# Generated by Django 3.2.18 on 2023-05-10 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quadraLote', '0005_lote_cliente'),
        ('controledeCheque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlecheque',
            name='lote_id',
        ),
        migrations.AddField(
            model_name='controlecheque',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LoteControleCheque', to='quadraLote.lote', verbose_name='lote'),
        ),
    ]
