# Generated by Django 3.2.18 on 2023-03-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('meses', models.IntegerField()),
                ('numero_intercalada', models.IntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parcela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('intercalada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('excluido', models.BooleanField(default=False)),
                ('data_exclusao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Parcelamentos',
                'ordering': ['id'],
            },
        ),
    ]
