# Generated by Django 3.2.18 on 2023-05-18 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcelamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcelamento',
            options={'verbose_name_plural': 'Parcelamentos'},
        ),
    ]
