# Generated by Django 3.2.18 on 2023-05-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='tipo',
            field=models.CharField(default='teste', max_length=100),
            preserve_default=False,
        ),
    ]
