# Generated by Django 3.2.18 on 2023-05-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0002_despesa_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
