# Generated by Django 3.2.18 on 2023-05-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0003_alter_despesa_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
