# Generated by Django 3.2.18 on 2023-05-18 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quadraLote', '0007_auto_20230517_2105'),
        ('despesas', '0004_despesa_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='despesa',
            name='data_referencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='despesa',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quadraLote.lote'),
        ),
    ]
