# Generated by Django 3.2.18 on 2023-06-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0007_despesa_devolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='geral',
            field=models.BooleanField(default=False),
        ),
    ]
